version: "3"

services:
  phoenix:
    build:
      context: .
      args:
        NODE_VERSION: 18.16.1
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: elixir_todo_dev
      PGHOST: db
      PGPORT: 5432
    depends_on:
      - db
    command:
      - "./entrypoint.sh"
  db:
    image: postgres:12.15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      # https://www.mend.io/free-developer-tools/blog/docker-expose-port/
      # Host Port: Container Port
      - 5433:5432
    volumes:
      - ./_pgdata:/var/lib/postgresql/data
